import { QueryInterface } from 'sequelize';

export default {
  async up(queryInterface: QueryInterface): Promise<void> {
    // Add Kieron Gillen as creator
    await queryInterface.bulkInsert(
      'Creators',
      [
        {
          id: 13,
          name: 'Kieron Gillen',
          creatorType: 'AUTHOR',
          bio: 'British comic book writer known for Darth Vader, Doctor Aphra, The Wicked + The Divine',
          birthDate: new Date('1975-09-30'),
          deathDate: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          name: 'Salvador Larroca',
          creatorType: 'ARTIST',
          bio: 'Spanish comic book artist known for his work on Darth Vader and various Marvel titles',
          birthDate: null,
          deathDate: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert the Darth Vader (2015) Run
    await queryInterface.bulkInsert(
      'Runs',
      [
        {
          id: 7,
          seriesName: 'Darth Vader (2015)',
          keyAuthorId: 13, // Kieron Gillen
          keyArtistId: 14, // Salvador Larroca
          startDate: new Date('2015-02-11'),
          endDate: new Date('2016-10-12'),
          startIssue: 1,
          endIssue: 25,
          description:
            'Marvel series following Darth Vader between A New Hope and Empire Strikes Back, exploring his investigation into Luke Skywalker',
          universeId: 5, // Star Wars Canon
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert Darth Vader (2015) Comics
    await queryInterface.bulkInsert(
      'Comics',
      [
        {
          id: 101,
          title: 'Darth Vader #1',
          authorId: 13, // Kieron Gillen
          description: 'Vader - After the destruction of the Death Star, Vader investigates',
          imageUrl: null,
          pages: 22,
          publisherId: 1, // Marvel Comics
          publishedDate: new Date('2015-02-11'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 102,
          title: 'Darth Vader #2',
          authorId: 13,
          description: 'Vader, Part II - Meeting with the Emperor',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-02-25'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 103,
          title: 'Darth Vader #3',
          authorId: 13,
          description: 'Vader, Part III - Recruiting allies',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-03-25'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 104,
          title: 'Darth Vader #4',
          authorId: 13,
          description: 'Vader, Part IV - Enter Doctor Aphra',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-04-08'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 105,
          title: 'Darth Vader #5',
          authorId: 13,
          description: 'Vader, Part V - Building a secret army',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-05-13'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 106,
          title: 'Darth Vader #6',
          authorId: 13,
          description: 'Vader, Part VI - Conclusion of first arc',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-06-03'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 107,
          title: 'Darth Vader #7',
          authorId: 13,
          description: 'Shadows and Secrets, Part I - New threats emerge',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-07-01'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 108,
          title: 'Darth Vader #8',
          authorId: 13,
          description: 'Shadows and Secrets, Part II - Corporate intrigue',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-08-05'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 109,
          title: 'Darth Vader #9',
          authorId: 13,
          description: 'Shadows and Secrets, Part III - Deeper conspiracies',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-09-09'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 110,
          title: 'Darth Vader #10',
          authorId: 13,
          description: 'Shadows and Secrets, Part IV - Dangerous missions',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-10-07'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 111,
          title: 'Darth Vader #11',
          authorId: 13,
          description: 'Shadows and Secrets, Part V - Imperial politics',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-10-21'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 112,
          title: 'Darth Vader #12',
          authorId: 13,
          description: 'Shadows and Secrets, Part VI - Arc conclusion',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-11-11'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 113,
          title: 'Darth Vader #13',
          authorId: 13,
          description: 'Vader Down, Part II - Vader surrounded by rebels',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-11-25'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 114,
          title: 'Darth Vader #14',
          authorId: 13,
          description: 'Vader Down, Part IV - The battle intensifies',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-12-23'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 115,
          title: 'Darth Vader #15',
          authorId: 13,
          description: 'Vader Down, Part VI - Conclusion of the crossover',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-01-06'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 116,
          title: 'Darth Vader Annual #1',
          authorId: 13,
          description: 'Annual: Exploring Vader and the Tusken Raiders',
          imageUrl: null,
          pages: 40,
          publisherId: 1,
          publishedDate: new Date('2015-12-16'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 117,
          title: 'Darth Vader #16',
          authorId: 13,
          description: 'The Shu-Torun War, Part I - Mining planet conflict',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-02-10'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 118,
          title: 'Darth Vader #17',
          authorId: 13,
          description: 'The Shu-Torun War, Part II - Escalating tensions',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-03-02'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 119,
          title: 'Darth Vader #18',
          authorId: 13,
          description: 'The Shu-Torun War, Part III - Full-scale war',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-03-30'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 120,
          title: 'Darth Vader #19',
          authorId: 13,
          description: 'The Shu-Torun War, Part IV - War conclusion',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-04-13'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 121,
          title: 'Darth Vader #20',
          authorId: 13,
          description: 'End of Games, Part I - The endgame begins',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-05-11'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 122,
          title: 'Darth Vader #21',
          authorId: 13,
          description: 'End of Games, Part II - Secrets revealed',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-06-08'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 123,
          title: 'Darth Vader #22',
          authorId: 13,
          description: 'End of Games, Part III - Betrayals',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-06-29'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 124,
          title: 'Darth Vader #23',
          authorId: 13,
          description: 'End of Games, Part IV - Final confrontations',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-07-20'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 125,
          title: 'Darth Vader #24',
          authorId: 13,
          description: 'End of Games, Part V - Penultimate chapter',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-08-10'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 126,
          title: 'Darth Vader #25',
          authorId: 13,
          description: 'End of Games, Part VI - Series finale',
          imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/darthvader-2025-25.jpg',
          pages: 40,
          publisherId: 1,
          publishedDate: new Date('2016-10-12'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert Trade Paperbacks for Darth Vader (2015)
    await queryInterface.bulkInsert(
      'TradePaperbacks',
      [
        {
          id: 5,
          title: 'Star Wars: Darth Vader Vol. 1: Vader',
          coverImageUrl: null,
          publicationDate: new Date('2015-10-06'),
          isbn: '9780785192558',
          description: 'Collects Darth Vader #1-6',
          pageCount: 144,
          publisherId: 1,
          volume: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          title: 'Star Wars: Darth Vader Vol. 2: Shadows and Secrets',
          coverImageUrl: null,
          publicationDate: new Date('2016-01-05'),
          isbn: '9780785192565',
          description: 'Collects Darth Vader #7-12',
          pageCount: 136,
          publisherId: 1,
          volume: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          title: 'Star Wars: Darth Vader Vol. 3: The Shu-Torun War',
          coverImageUrl: null,
          publicationDate: new Date('2016-08-09'),
          isbn: '9780785199779',
          description: 'Collects Darth Vader Annual #1, Darth Vader #16-19',
          pageCount: 112,
          publisherId: 1,
          volume: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          title: 'Star Wars: Darth Vader Vol. 4: End of Games',
          coverImageUrl: null,
          publicationDate: new Date('2016-11-23'),
          isbn: '9781302901103',
          description: 'Collects Darth Vader #20-25',
          pageCount: 144,
          publisherId: 1,
          volume: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert Omnibus edition
    await queryInterface.bulkInsert(
      'Omnibuses',
      [
        {
          id: 3,
          title: 'Star Wars: Darth Vader by Kieron Gillen Omnibus',
          coverImageUrl: null,
          publicationDate: new Date('2017-09-19'),
          isbn: '9781302908218',
          description: 'The complete Kieron Gillen run collecting Darth Vader #1-25 and Annual #1',
          pageCount: 648,
          publisherId: 1,
          volume: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Create relationships between Trade Paperbacks and Comics
    await queryInterface.bulkInsert(
      'TradePaperbackComicXRefs',
      [
        // Vol. 1: Vader (Issues #1-6)
        {
          tradePaperbackId: 5,
          comicId: 101,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 102,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 103,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 104,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 105,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 106,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // Vol. 2: Shadows and Secrets (Issues #7-12)
        {
          tradePaperbackId: 6,
          comicId: 107,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 108,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 109,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 110,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 111,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 112,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // Vol. 3: The Shu-Torun War (Annual #1, Issues #16-19)
        {
          tradePaperbackId: 7,
          comicId: 116,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 7,
          comicId: 117,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 7,
          comicId: 118,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 7,
          comicId: 119,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 7,
          comicId: 120,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // Vol. 4: End of Games (Issues #20-25)
        {
          tradePaperbackId: 8,
          comicId: 121,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 122,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 123,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 124,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 125,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 126,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Create relationships between Omnibus and Comics
    const vaderOmnibusComics = [
      101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
      120, 121, 122, 123, 124, 125, 126,
    ];
    await queryInterface.bulkInsert(
      'OmnibusComicXRefs',
      vaderOmnibusComics.map((comicId, index) => ({
        omnibusId: 3,
        comicId,
        orderInCollection: index + 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      })),
      {}
    );
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    // Delete in reverse order due to foreign keys
    await queryInterface.bulkDelete('OmnibusComicXRefs', { omnibusId: 3 }, {});
    await queryInterface.bulkDelete(
      'TradePaperbackComicXRefs',
      { tradePaperbackId: [5, 6, 7, 8] },
      {}
    );
    await queryInterface.bulkDelete('Omnibuses', { id: 3 }, {});
    await queryInterface.bulkDelete('TradePaperbacks', { id: [5, 6, 7, 8] }, {});
    await queryInterface.bulkDelete(
      'Comics',
      {
        id: [
          101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
          119, 120, 121, 122, 123, 124, 125, 126,
        ],
      },
      {}
    );
    await queryInterface.bulkDelete('Runs', { id: 7 }, {});
    await queryInterface.bulkDelete('Creators', { id: [13, 14] }, {});
  },
};
