import { QueryInterface } from 'sequelize';

export default {
  async up(queryInterface: QueryInterface) {
    // Insert Fantastic Four Vol 1 run
    await queryInterface.bulkInsert('Runs', [
      {
        id: 9,
        seriesName: 'Fantastic Four Vol 1',
        keyAuthorId: 1, // Stan Lee
        keyArtistId: 2, // Jack Kirby
        startDate: new Date('1961-11-08'),
        endDate: new Date('1996-09-01'),
        startIssue: 1,
        endIssue: 416,
        description: 'The original Fantastic Four series that launched the Marvel Age of Comics.',
        universeId: 2, // Marvel Universe
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);

    // Insert 50 Fantastic Four comics (issues 108-157)
    await queryInterface.bulkInsert('Comics', [
      {
        id: 108,
        title: 'Fantastic Four #1',
        authorId: 1, // Stan Lee
        description: 'First appearance of the Fantastic Four, Mole Man, and Monster Isle!',
        imageUrl: null,
        pages: null,
        publisherId: 1, // Marvel
        publishedDate: new Date('1961-11-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 109,
        title: 'Fantastic Four #2',
        authorId: 1,
        description: 'The Fantastic Four Meet the Skrulls from Outer Space!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1961-09-28'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 110,
        title: 'Fantastic Four #3',
        authorId: 1,
        description: 'The Menace of the Miracle Man',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1961-12-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 111,
        title: 'Fantastic Four #4',
        authorId: 1,
        description: 'The Coming of... Sub-Mariner!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-02-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 112,
        title: 'Fantastic Four #5',
        authorId: 1,
        description: 'Prisoners of Doctor Doom! First appearance of Doctor Doom.',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-04-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 113,
        title: 'Fantastic Four #6',
        authorId: 1,
        description: 'Captives of the Deadly Duo!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-06-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 114,
        title: 'Fantastic Four #7',
        authorId: 1,
        description: 'Prisoners of Kurrgo, Master of Planet X',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-07-03'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 115,
        title: 'Fantastic Four #8',
        authorId: 1,
        description: 'Prisoners of the Puppet Master!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-08-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 116,
        title: 'Fantastic Four #9',
        authorId: 1,
        description: 'The End of the Fantastic Four!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-09-04'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 117,
        title: 'Fantastic Four #10',
        authorId: 1,
        description: 'The Return of Doctor Doom!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-10-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 118,
        title: 'Fantastic Four #11',
        authorId: 1,
        description: 'A Visit With the Fantastic Four',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-11-01'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 119,
        title: 'Fantastic Four #12',
        authorId: 1,
        description: 'The Incredible Hulk - First meeting of FF and Hulk',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-12-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 120,
        title: 'Fantastic Four #13',
        authorId: 1,
        description: 'The Fantastic Four Versus the Red Ghost and His Indescribable Super-Apes!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-01-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 121,
        title: 'Fantastic Four #14',
        authorId: 1,
        description: 'The Merciless Puppet Master',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-02-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 122,
        title: 'Fantastic Four #15',
        authorId: 1,
        description: 'The Fantastic Four Battle the Mad Thinker and His Awesome Android!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-03-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 123,
        title: 'Fantastic Four #16',
        authorId: 1,
        description: 'The Micro-World of Doctor Doom!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-04-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 124,
        title: 'Fantastic Four #17',
        authorId: 1,
        description: 'Defeated by Doctor Doom!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-05-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 125,
        title: 'Fantastic Four #18',
        authorId: 1,
        description: 'A Skrull Walks Among Us!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-06-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 126,
        title: 'Fantastic Four #19',
        authorId: 1,
        description: 'Prisoners of the Pharoah!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-07-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 127,
        title: 'Fantastic Four #20',
        authorId: 1,
        description: 'The Mysterious Molecule Man!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-08-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 128,
        title: 'Fantastic Four #21',
        authorId: 1,
        description: 'The Hate-Monger!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-09-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 129,
        title: 'Fantastic Four #22',
        authorId: 1,
        description: 'The Return of the Mole Man!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-10-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 130,
        title: 'Fantastic Four #23',
        authorId: 1,
        description: 'The Master Plan of Doctor Doom!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-11-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 131,
        title: 'Fantastic Four #24',
        authorId: 1,
        description: 'The Infant Terrible!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-12-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 132,
        title: 'Fantastic Four #25',
        authorId: 1,
        description: 'The Hulk Vs. the Thing',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-01-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 133,
        title: 'Fantastic Four #26',
        authorId: 1,
        description: 'The Avengers Take Over!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-02-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 134,
        title: 'Fantastic Four #27',
        authorId: 1,
        description: 'The Search for Sub-Mariner!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-03-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 135,
        title: 'Fantastic Four #28',
        authorId: 1,
        description: 'We Have to Fight the X-Men!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-04-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 136,
        title: 'Fantastic Four #29',
        authorId: 1,
        description: 'It Started on Yancy Street!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-05-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 137,
        title: 'Fantastic Four #30',
        authorId: 1,
        description: 'The Dreaded Diablo!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-06-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 138,
        title: 'Fantastic Four #31',
        authorId: 1,
        description: 'The Mad Menace of the Macabre Mole Man',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-07-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 139,
        title: 'Fantastic Four #32',
        authorId: 1,
        description: 'Death of a Hero!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-08-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 140,
        title: 'Fantastic Four #33',
        authorId: 1,
        description: 'Side-By-Side with Sub-Mariner!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-09-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 141,
        title: 'Fantastic Four #34',
        authorId: 1,
        description: 'A House Divided!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-10-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 142,
        title: 'Fantastic Four #35',
        authorId: 1,
        description: 'Calamity on the Campus!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-11-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 143,
        title: 'Fantastic Four #36',
        authorId: 1,
        description: 'The Frightful Four! First appearance of Medusa.',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-12-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 144,
        title: 'Fantastic Four #37',
        authorId: 1,
        description: 'Behold! A Distant Star!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-01-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 145,
        title: 'Fantastic Four #38',
        authorId: 1,
        description: 'Defeated by the Frightful Four!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-02-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 146,
        title: 'Fantastic Four #39',
        authorId: 1,
        description: 'A Blind Man Shall Lead Them! - Daredevil appearance',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-03-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 147,
        title: 'Fantastic Four #40',
        authorId: 1,
        description: 'The Battle of the Baxter Building',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-04-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 148,
        title: 'Fantastic Four #41',
        authorId: 1,
        description: 'The Brutal Betrayal of Ben Grimm!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-05-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 149,
        title: 'Fantastic Four #42',
        authorId: 1,
        description: 'The Battle of the Baxter Building (Part 2)',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-06-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 150,
        title: 'Fantastic Four #43',
        authorId: 1,
        description: 'Lo! There Shall Come... An Ending!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-07-13'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 151,
        title: 'Fantastic Four #44',
        authorId: 1,
        description: "The Gentleman's Name is Gorgon! First appearance of Gorgon.",
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-08-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 152,
        title: 'Fantastic Four #45',
        authorId: 1,
        description: 'Among Us Hide... The Inhumans - First appearance of the Inhumans.',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-09-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 153,
        title: 'Fantastic Four #46',
        authorId: 1,
        description: 'Those Who Would Destroy Us',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-10-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 154,
        title: 'Fantastic Four #47',
        authorId: 1,
        description: 'Beware the Hidden Land!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-11-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 155,
        title: 'Fantastic Four #48',
        authorId: 1,
        description: 'The Coming of Galactus! First appearance of Galactus and Silver Surfer.',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-12-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 156,
        title: 'Fantastic Four #49',
        authorId: 1,
        description: 'If This Be Doomsday!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1966-01-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 157,
        title: 'Fantastic Four #50',
        authorId: 1,
        description: 'The Startling Saga of the Silver Surfer!',
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1966-02-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);

    // Insert Trade Paperbacks
    await queryInterface.bulkInsert('TradePaperbacks', [
      {
        id: 14,
        title: "Fantastic Four Epic Collection: The World's Greatest Comic Magazine",
        coverImageUrl: null,
        publicationDate: new Date('2014-08-20'),
        isbn: '9780785188643',
        description: 'Collects Fantastic Four (1961) #1-18 and Annual #1',
        pageCount: 472,
        publisherId: 1,
        volume: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        title: 'Fantastic Four by Stan Lee and Jack Kirby Omnibus Vol. 1',
        coverImageUrl: null,
        publicationDate: new Date('2013-11-27'),
        isbn: '9780785185680',
        description: 'Collects Fantastic Four (1961) #1-30 and Annual #1',
        pageCount: 848,
        publisherId: 1,
        volume: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        title: 'Fantastic Four by Stan Lee and Jack Kirby Omnibus Vol. 2',
        coverImageUrl: null,
        publicationDate: new Date('2020-02-18'),
        isbn: '9781302920524',
        description: 'Collects Fantastic Four (1961) #31-60 and Annual #2-4',
        pageCount: 944,
        publisherId: 1,
        volume: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        title: 'Fantastic Four Masterworks Vol. 1',
        coverImageUrl: null,
        publicationDate: new Date('2009-11-04'),
        isbn: '9780785142577',
        description: 'Collects Fantastic Four (1961) #1-10',
        pageCount: 224,
        publisherId: 1,
        volume: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        title: 'Fantastic Four: The Trial of Galactus',
        coverImageUrl: null,
        publicationDate: new Date('2010-03-03'),
        isbn: '9780785145738',
        description: 'Collects Fantastic Four (1961) #242-244 and #257-262',
        pageCount: 216,
        publisherId: 1,
        volume: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface: QueryInterface) {
    // Delete in reverse order to respect foreign key constraints
    await queryInterface.bulkDelete('TradePaperbacks', { id: [14, 15, 16, 17, 18] });
    await queryInterface.bulkDelete('Comics', {
      id: Array.from({ length: 50 }, (_, i) => 108 + i), // IDs 108-157
    });
    await queryInterface.bulkDelete('Runs', { id: 9 });
  },
};
