import { QueryInterface } from 'sequelize';

export default {
  async up(queryInterface: QueryInterface): Promise<void> {
    // Add Kieron Gillen as creator
    await queryInterface.bulkInsert(
      'Creators',
      [
        {
          id: 13,
          name: 'Kieron Gillen',
          creatorType: 'AUTHOR',
          bio: 'British comic book writer known for Darth Vader, Doctor Aphra, The Wicked + The Divine',
          birthDate: new Date('1975-09-30'),
          deathDate: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          name: 'Salvador Larroca',
          creatorType: 'ARTIST',
          bio: 'Spanish comic book artist known for his work on Darth Vader and various Marvel titles',
          birthDate: null,
          deathDate: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert the Darth Vader (2015) Run
    await queryInterface.bulkInsert(
      'Runs',
      [
        {
          id: 7,
          seriesName: 'Darth Vader (2015)',
          keyAuthorId: 13, // Kieron Gillen
          keyArtistId: 14, // Salvador Larroca
          startDate: new Date('2015-02-11'),
          endDate: new Date('2016-10-12'),
          startIssue: 1,
          endIssue: 25,
          description:
            'Marvel series following Darth Vader between A New Hope and Empire Strikes Back, exploring his investigation into Luke Skywalker',
          universeId: 5, // Star Wars Canon
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert Darth Vader (2015) Comics
    await queryInterface.bulkInsert(
      'Comics',
      [
        {
          id: 32,
          title: 'Darth Vader #1',
          authorId: 13, // Kieron Gillen
          description: 'Vader - After the destruction of the Death Star, Vader investigates',
          imageUrl: null,
          pages: 22,
          publisherId: 1, // Marvel Comics
          publishedDate: new Date('2015-02-11'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 33,
          title: 'Darth Vader #2',
          authorId: 13,
          description: 'Vader, Part II - Meeting with the Emperor',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-02-25'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 34,
          title: 'Darth Vader #3',
          authorId: 13,
          description: 'Vader, Part III - Recruiting allies',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-03-25'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 35,
          title: 'Darth Vader #4',
          authorId: 13,
          description: 'Vader, Part IV - Enter Doctor Aphra',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-04-08'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 36,
          title: 'Darth Vader #5',
          authorId: 13,
          description: 'Vader, Part V - Building a secret army',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-05-13'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 37,
          title: 'Darth Vader #6',
          authorId: 13,
          description: 'Vader, Part VI - Conclusion of first arc',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-06-03'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 38,
          title: 'Darth Vader #7',
          authorId: 13,
          description: 'Shadows and Secrets, Part I - New threats emerge',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-07-01'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 39,
          title: 'Darth Vader #8',
          authorId: 13,
          description: 'Shadows and Secrets, Part II - Corporate intrigue',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-08-05'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 40,
          title: 'Darth Vader #9',
          authorId: 13,
          description: 'Shadows and Secrets, Part III - Deeper conspiracies',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-09-09'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 41,
          title: 'Darth Vader #10',
          authorId: 13,
          description: 'Shadows and Secrets, Part IV - Dangerous missions',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-10-07'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 42,
          title: 'Darth Vader #11',
          authorId: 13,
          description: 'Shadows and Secrets, Part V - Imperial politics',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-10-21'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 43,
          title: 'Darth Vader #12',
          authorId: 13,
          description: 'Shadows and Secrets, Part VI - Arc conclusion',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-11-11'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 44,
          title: 'Darth Vader #13',
          authorId: 13,
          description: 'Vader Down, Part II - Vader surrounded by rebels',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-11-25'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 45,
          title: 'Darth Vader #14',
          authorId: 13,
          description: 'Vader Down, Part IV - The battle intensifies',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2015-12-23'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 46,
          title: 'Darth Vader #15',
          authorId: 13,
          description: 'Vader Down, Part VI - Conclusion of the crossover',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-01-06'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 47,
          title: 'Darth Vader Annual #1',
          authorId: 13,
          description: 'Annual: Exploring Vader and the Tusken Raiders',
          imageUrl: null,
          pages: 40,
          publisherId: 1,
          publishedDate: new Date('2015-12-16'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 48,
          title: 'Darth Vader #16',
          authorId: 13,
          description: 'The Shu-Torun War, Part I - Mining planet conflict',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-02-10'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 49,
          title: 'Darth Vader #17',
          authorId: 13,
          description: 'The Shu-Torun War, Part II - Escalating tensions',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-03-02'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 50,
          title: 'Darth Vader #18',
          authorId: 13,
          description: 'The Shu-Torun War, Part III - Full-scale war',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-03-30'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 51,
          title: 'Darth Vader #19',
          authorId: 13,
          description: 'The Shu-Torun War, Part IV - War conclusion',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-04-13'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 52,
          title: 'Darth Vader #20',
          authorId: 13,
          description: 'End of Games, Part I - The endgame begins',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-05-11'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 53,
          title: 'Darth Vader #21',
          authorId: 13,
          description: 'End of Games, Part II - Secrets revealed',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-06-08'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 54,
          title: 'Darth Vader #22',
          authorId: 13,
          description: 'End of Games, Part III - Betrayals',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-06-29'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 55,
          title: 'Darth Vader #23',
          authorId: 13,
          description: 'End of Games, Part IV - Final confrontations',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-07-20'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 56,
          title: 'Darth Vader #24',
          authorId: 13,
          description: 'End of Games, Part V - Penultimate chapter',
          imageUrl: null,
          pages: 20,
          publisherId: 1,
          publishedDate: new Date('2016-08-10'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 57,
          title: 'Darth Vader #25',
          authorId: 13,
          description: 'End of Games, Part VI - Series finale',
          imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/darthvader-2025-25.jpg',
          pages: 40,
          publisherId: 1,
          publishedDate: new Date('2016-10-12'),
          runId: 7,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert Trade Paperbacks for Darth Vader (2015)
    await queryInterface.bulkInsert(
      'TradePaperbacks',
      [
        {
          id: 5,
          title: 'Star Wars: Darth Vader Vol. 1: Vader',
          coverImageUrl: null,
          publicationDate: new Date('2015-10-06'),
          isbn: '9780785192558',
          description: 'Collects Darth Vader #1-6',
          pageCount: 144,
          publisherId: 1,
          volume: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          title: 'Star Wars: Darth Vader Vol. 2: Shadows and Secrets',
          coverImageUrl: null,
          publicationDate: new Date('2016-01-05'),
          isbn: '9780785192565',
          description: 'Collects Darth Vader #7-12',
          pageCount: 136,
          publisherId: 1,
          volume: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          title: 'Star Wars: Darth Vader Vol. 3: The Shu-Torun War',
          coverImageUrl: null,
          publicationDate: new Date('2016-08-09'),
          isbn: '9780785199779',
          description: 'Collects Darth Vader Annual #1, Darth Vader #16-19',
          pageCount: 112,
          publisherId: 1,
          volume: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          title: 'Star Wars: Darth Vader Vol. 4: End of Games',
          coverImageUrl: null,
          publicationDate: new Date('2016-11-23'),
          isbn: '9781302901103',
          description: 'Collects Darth Vader #20-25',
          pageCount: 144,
          publisherId: 1,
          volume: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert Omnibus edition
    await queryInterface.bulkInsert(
      'Omnibuses',
      [
        {
          id: 3,
          title: 'Star Wars: Darth Vader by Kieron Gillen Omnibus',
          coverImageUrl: null,
          publicationDate: new Date('2017-09-19'),
          isbn: '9781302908218',
          description: 'The complete Kieron Gillen run collecting Darth Vader #1-25 and Annual #1',
          pageCount: 648,
          publisherId: 1,
          volume: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Create relationships between Trade Paperbacks and Comics
    await queryInterface.bulkInsert(
      'TradePaperbackComicXRefs',
      [
        // Vol. 1: Vader (Issues #1-6)
        {
          tradePaperbackId: 5,
          comicId: 32,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 33,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 34,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 35,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 36,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 5,
          comicId: 37,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // Vol. 2: Shadows and Secrets (Issues #7-12)
        {
          tradePaperbackId: 6,
          comicId: 38,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 39,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 40,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 41,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 42,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 6,
          comicId: 43,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // Vol. 3: The Shu-Torun War (Annual #1, Issues #16-19)
        {
          tradePaperbackId: 7,
          comicId: 47,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 7,
          comicId: 48,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 7,
          comicId: 49,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 7,
          comicId: 50,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 7,
          comicId: 51,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // Vol. 4: End of Games (Issues #20-25)
        {
          tradePaperbackId: 8,
          comicId: 52,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 53,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 54,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 55,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 56,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          tradePaperbackId: 8,
          comicId: 57,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Create relationships between Omnibus and Comics
    const vaderOmnibusComics = [
      32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
      55, 56, 57,
    ];
    await queryInterface.bulkInsert(
      'OmnibusComicXRefs',
      vaderOmnibusComics.map((comicId, index) => ({
        omnibusId: 3,
        comicId,
        orderInCollection: index + 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      })),
      {}
    );
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    // Delete in reverse order due to foreign keys
    await queryInterface.bulkDelete('OmnibusComicXRefs', { omnibusId: 3 }, {});
    await queryInterface.bulkDelete(
      'TradePaperbackComicXRefs',
      { tradePaperbackId: [5, 6, 7, 8] },
      {}
    );
    await queryInterface.bulkDelete('Omnibuses', { id: 3 }, {});
    await queryInterface.bulkDelete('TradePaperbacks', { id: [5, 6, 7, 8] }, {});
    await queryInterface.bulkDelete(
      'Comics',
      {
        id: [
          32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
          54, 55, 56, 57,
        ],
      },
      {}
    );
    await queryInterface.bulkDelete('Runs', { id: 7 }, {});
    await queryInterface.bulkDelete('Creators', { id: [13, 14] }, {});
  },
};
