import { QueryInterface } from 'sequelize';

export default {
  async up(queryInterface: QueryInterface) {
    // Insert Fantastic Four Vol 1 run
    await queryInterface.bulkInsert('Runs', [
      {
        id: 9,
        seriesName: 'Fantastic Four Vol 1',
        keyAuthorId: 1, // Stan Lee
        keyArtistId: 2, // Jack Kirby
        startDate: new Date('1961-11-08'),
        endDate: new Date('1996-09-01'),
        startIssue: 1,
        endIssue: 416,
        description: 'The original Fantastic Four series that launched the Marvel Age of Comics.',
        universeId: 2, // Marvel Universe
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);

    // Insert 50 Fantastic Four comics (issues 108-157)
    await queryInterface.bulkInsert('Comics', [
      {
        id: 2001,
        title: 'Fantastic Four #1',
        authorId: 1, // Stan Lee
        description: 'First appearance of the Fantastic Four, Mole Man, and Monster Isle!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-1.jpg',
        pages: null,
        publisherId: 1, // Marvel
        publishedDate: new Date('1961-11-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2002,
        title: 'Fantastic Four #2',
        authorId: 1,
        description: 'The Fantastic Four Meet the Skrulls from Outer Space!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-2.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1961-09-28'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2003,
        title: 'Fantastic Four #3',
        authorId: 1,
        description: 'The Menace of the Miracle Man',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-3.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1961-12-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2004,
        title: 'Fantastic Four #4',
        authorId: 1,
        description: 'The Coming of... Sub-Mariner!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-4.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-02-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2005,
        title: 'Fantastic Four #5',
        authorId: 1,
        description: 'Prisoners of Doctor Doom! First appearance of Doctor Doom.',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-5.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-04-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2006,
        title: 'Fantastic Four #6',
        authorId: 1,
        description: 'Captives of the Deadly Duo!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-6.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-06-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2007,
        title: 'Fantastic Four #7',
        authorId: 1,
        description: 'Prisoners of Kurrgo, Master of Planet X',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-7.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-07-03'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2008,
        title: 'Fantastic Four #8',
        authorId: 1,
        description: 'Prisoners of the Puppet Master!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-8.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-08-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2009,
        title: 'Fantastic Four #9',
        authorId: 1,
        description: 'The End of the Fantastic Four!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-9.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-09-04'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2010,
        title: 'Fantastic Four #10',
        authorId: 1,
        description: 'The Return of Doctor Doom!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-10.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-10-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2011,
        title: 'Fantastic Four #11',
        authorId: 1,
        description: 'A Visit With the Fantastic Four',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-11.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-11-01'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2012,
        title: 'Fantastic Four #12',
        authorId: 1,
        description: 'The Incredible Hulk - First meeting of FF and Hulk',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-12.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1962-12-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2013,
        title: 'Fantastic Four #13',
        authorId: 1,
        description: 'The Fantastic Four Versus the Red Ghost and His Indescribable Super-Apes!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-13.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-01-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2014,
        title: 'Fantastic Four #14',
        authorId: 1,
        description: 'The Merciless Puppet Master',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-14.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-02-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2015,
        title: 'Fantastic Four #15',
        authorId: 1,
        description: 'The Fantastic Four Battle the Mad Thinker and His Awesome Android!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-15.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-03-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2016,
        title: 'Fantastic Four #16',
        authorId: 1,
        description: 'The Micro-World of Doctor Doom!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-16.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-04-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2017,
        title: 'Fantastic Four #17',
        authorId: 1,
        description: 'Defeated by Doctor Doom!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-17.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-05-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2018,
        title: 'Fantastic Four #18',
        authorId: 1,
        description: 'A Skrull Walks Among Us!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-18.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-06-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2019,
        title: 'Fantastic Four #19',
        authorId: 1,
        description: 'Prisoners of the Pharoah!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-19.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-07-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2020,
        title: 'Fantastic Four #20',
        authorId: 1,
        description: 'The Mysterious Molecule Man!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-20.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-08-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2021,
        title: 'Fantastic Four #21',
        authorId: 1,
        description: 'The Hate-Monger!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-21.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-09-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2022,
        title: 'Fantastic Four #22',
        authorId: 1,
        description: 'The Return of the Mole Man!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-22.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-10-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2023,
        title: 'Fantastic Four #23',
        authorId: 1,
        description: 'The Master Plan of Doctor Doom!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-23.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-11-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2024,
        title: 'Fantastic Four #24',
        authorId: 1,
        description: 'The Infant Terrible!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-24.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1963-12-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2025,
        title: 'Fantastic Four #25',
        authorId: 1,
        description: 'The Hulk Vs. the Thing',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-25.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-01-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2026,
        title: 'Fantastic Four #26',
        authorId: 1,
        description: 'The Avengers Take Over!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-26.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-02-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2027,
        title: 'Fantastic Four #27',
        authorId: 1,
        description: 'The Search for Sub-Mariner!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-27.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-03-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2028,
        title: 'Fantastic Four #28',
        authorId: 1,
        description: 'We Have to Fight the X-Men!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-28.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-04-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2029,
        title: 'Fantastic Four #29',
        authorId: 1,
        description: 'It Started on Yancy Street!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-29.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-05-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2030,
        title: 'Fantastic Four #30',
        authorId: 1,
        description: 'The Dreaded Diablo!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-30.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-06-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2031,
        title: 'Fantastic Four #31',
        authorId: 1,
        description: 'The Mad Menace of the Macabre Mole Man',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-31.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-07-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2032,
        title: 'Fantastic Four #32',
        authorId: 1,
        description: 'Death of a Hero!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-32.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-08-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2033,
        title: 'Fantastic Four #33',
        authorId: 1,
        description: 'Side-By-Side with Sub-Mariner!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-33.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-09-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2034,
        title: 'Fantastic Four #34',
        authorId: 1,
        description: 'A House Divided!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-34.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-10-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2035,
        title: 'Fantastic Four #35',
        authorId: 1,
        description: 'Calamity on the Campus!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-35.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-11-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2036,
        title: 'Fantastic Four #36',
        authorId: 1,
        description: 'The Frightful Four! First appearance of Medusa.',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-36.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1964-12-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2037,
        title: 'Fantastic Four #37',
        authorId: 1,
        description: 'Behold! A Distant Star!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-37.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-01-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2038,
        title: 'Fantastic Four #38',
        authorId: 1,
        description: 'Defeated by the Frightful Four!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-38.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-02-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2039,
        title: 'Fantastic Four #39',
        authorId: 1,
        description: 'A Blind Man Shall Lead Them! - Daredevil appearance',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-39.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-03-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2040,
        title: 'Fantastic Four #40',
        authorId: 1,
        description: 'The Battle of the Baxter Building',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-40.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-04-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2041,
        title: 'Fantastic Four #41',
        authorId: 1,
        description: 'The Brutal Betrayal of Ben Grimm!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-41.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-05-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2042,
        title: 'Fantastic Four #42',
        authorId: 1,
        description: 'The Battle of the Baxter Building (Part 2)',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-42.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-06-08'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2043,
        title: 'Fantastic Four #43',
        authorId: 1,
        description: 'Lo! There Shall Come... An Ending!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-43.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-07-13'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2044,
        title: 'Fantastic Four #44',
        authorId: 1,
        description: "The Gentleman's Name is Gorgon! First appearance of Gorgon.",
        imageUrl: null,
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-08-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2045,
        title: 'Fantastic Four #45',
        authorId: 1,
        description: 'Among Us Hide... The Inhumans - First appearance of the Inhumans.',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-45.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-09-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2046,
        title: 'Fantastic Four #46',
        authorId: 1,
        description: 'Those Who Would Destroy Us',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-46.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-10-12'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2047,
        title: 'Fantastic Four #47',
        authorId: 1,
        description: 'Beware the Hidden Land!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-47.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-11-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2048,
        title: 'Fantastic Four #48',
        authorId: 1,
        description: 'The Coming of Galactus! First appearance of Galactus and Silver Surfer.',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-48.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1965-12-09'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2049,
        title: 'Fantastic Four #49',
        authorId: 1,
        description: 'If This Be Doomsday!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-49.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1966-01-11'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2050,
        title: 'Fantastic Four #50',
        authorId: 1,
        description: 'The Startling Saga of the Silver Surfer!',
        imageUrl: 'https://comics-tracker-2025.s3.us-east-1.amazonaws.com/ff-1961-50.jpg',
        pages: null,
        publisherId: 1,
        publishedDate: new Date('1966-02-10'),
        runId: 9,
        variant: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);

    // Insert Trade Paperbacks
    await queryInterface.bulkInsert('TradePaperbacks', [
      {
        id: 14,
        title: "Fantastic Four Epic Collection: The World's Greatest Comic Magazine",
        coverImageUrl: null,
        publicationDate: new Date('2014-08-20'),
        isbn: '9780785188643',
        description: 'Collects Fantastic Four (1961) #1-18 and Annual #1',
        pageCount: 472,
        publisherId: 1,
        volume: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        title: 'Fantastic Four by Stan Lee and Jack Kirby Omnibus Vol. 1',
        coverImageUrl: null,
        publicationDate: new Date('2013-11-27'),
        isbn: '9780785185680',
        description: 'Collects Fantastic Four (1961) #1-30 and Annual #1',
        pageCount: 848,
        publisherId: 1,
        volume: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        title: 'Fantastic Four by Stan Lee and Jack Kirby Omnibus Vol. 2',
        coverImageUrl: null,
        publicationDate: new Date('2020-02-18'),
        isbn: '9781302920524',
        description: 'Collects Fantastic Four (1961) #31-60 and Annual #2-4',
        pageCount: 944,
        publisherId: 1,
        volume: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        title: 'Fantastic Four Masterworks Vol. 1',
        coverImageUrl: null,
        publicationDate: new Date('2009-11-04'),
        isbn: '9780785142577',
        description: 'Collects Fantastic Four (1961) #1-10',
        pageCount: 224,
        publisherId: 1,
        volume: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        title: 'Fantastic Four: The Trial of Galactus',
        coverImageUrl: null,
        publicationDate: new Date('2010-03-03'),
        isbn: '9780785145738',
        description: 'Collects Fantastic Four (1961) #242-244 and #257-262',
        pageCount: 216,
        publisherId: 1,
        volume: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface: QueryInterface) {
    // Delete in reverse order to respect foreign key constraints
    await queryInterface.bulkDelete('TradePaperbacks', { id: [14, 15, 16, 17, 18] });
    await queryInterface.bulkDelete('Comics', {
      id: Array.from({ length: 50 }, (_, i) => 108 + i), // IDs 108-157
    });
    await queryInterface.bulkDelete('Runs', { id: 9 });
  },
};
