import { QueryInterface } from 'sequelize';

export default {
  async up(queryInterface: QueryInterface): Promise<void> {
    // Add Steve Ditko and John Romita Sr. as creators (Stan Lee already exists with ID 1)
    await queryInterface.bulkInsert(
      'Creators',
      [
        {
          id: 16,
          name: 'Steve Ditko',
          creatorType: 'ARTIST',
          bio: 'Legendary comic book artist, co-creator of Spider-Man and Doctor Strange. Known for his distinctive art style.',
          birthDate: new Date('1927-11-02'),
          deathDate: new Date('2018-06-29'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          name: 'John Romita Sr.',
          creatorType: 'ARTIST',
          bio: "Legendary comic book artist who succeeded Steve Ditko on Amazing Spider-Man and defined the character's look for decades.",
          birthDate: new Date('1930-01-24'),
          deathDate: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert the Amazing Spider-Man Vol 1 Run
    await queryInterface.bulkInsert(
      'Runs',
      [
        {
          id: 8,
          seriesName: 'The Amazing Spider-Man Vol 1',
          keyAuthorId: 1, // Stan Lee
          keyArtistId: 16, // Steve Ditko
          startDate: new Date('1963-03-01'),
          endDate: new Date('1998-11-01'),
          startIssue: 1,
          endIssue: 441,
          description:
            "The original and longest-running Spider-Man series, featuring Peter Parker's adventures from his high school days through college and beyond.",
          universeId: 2, // Marvel 616
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert Comics (Issues #1-50)
    await queryInterface.bulkInsert(
      'Comics',
      [
        {
          id: 58,
          title: 'The Amazing Spider-Man #1',
          authorId: 1, // Stan Lee
          description: 'Spider-Man! - First appearance of J. Jonah Jameson and the Chameleon',
          imageUrl: null,
          pages: 22,
          publisherId: 1, // Marvel Comics
          publishedDate: new Date('1963-03-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 59,
          title: 'The Amazing Spider-Man #2',
          authorId: 1,
          description: 'Duel to the Death with the Vulture! - First appearance of the Vulture',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1963-05-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 60,
          title: 'The Amazing Spider-Man #3',
          authorId: 1,
          description: 'Spider-Man Versus Doctor Octopus - First appearance of Doctor Octopus',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1963-07-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 61,
          title: 'The Amazing Spider-Man #4',
          authorId: 1,
          description: 'Nothing Can Stop... the Sandman! - First appearance of the Sandman',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1963-09-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 62,
          title: 'The Amazing Spider-Man #5',
          authorId: 1,
          description: 'Marked for Destruction by Dr. Doom! - Doctor Doom appearance',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1963-10-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 63,
          title: 'The Amazing Spider-Man #6',
          authorId: 1,
          description: 'Face-to-Face with... the Lizard! - First appearance of the Lizard',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1963-11-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 64,
          title: 'The Amazing Spider-Man #7',
          authorId: 1,
          description: 'The Return of the Vulture - Vulture returns',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1963-12-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 65,
          title: 'The Amazing Spider-Man #8',
          authorId: 1,
          description: 'The Terrible Threat of the Living Brain!',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-01-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 66,
          title: 'The Amazing Spider-Man #9',
          authorId: 1,
          description: 'The Man Called Electro! - First appearance of Electro',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-02-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 67,
          title: 'The Amazing Spider-Man #10',
          authorId: 1,
          description: 'The Enforcers! - First appearance of the Enforcers',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-03-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 68,
          title: 'The Amazing Spider-Man #11',
          authorId: 1,
          description: 'Turning Point - Second appearance of Doctor Octopus',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-04-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 69,
          title: 'The Amazing Spider-Man #12',
          authorId: 1,
          description: 'Unmasked By Doctor Octopus!',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-05-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 70,
          title: 'The Amazing Spider-Man #13',
          authorId: 1,
          description: 'The Menace of... Mysterio! - First appearance of Mysterio',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-06-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 71,
          title: 'The Amazing Spider-Man #14',
          authorId: 1,
          description:
            'The Grotesque Adventure of the Green Goblin - First appearance of the Green Goblin',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-07-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 72,
          title: 'The Amazing Spider-Man #15',
          authorId: 1,
          description: 'Kraven the Hunter! - First appearance of Kraven the Hunter',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-08-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 73,
          title: 'The Amazing Spider-Man #16',
          authorId: 1,
          description: 'Duel with Daredevil - First meeting with Daredevil',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-09-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 74,
          title: 'The Amazing Spider-Man #17',
          authorId: 1,
          description: 'The Return of the Green Goblin!',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-10-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 75,
          title: 'The Amazing Spider-Man #18',
          authorId: 1,
          description: 'The End of Spider-Man! - Sandman appearance',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-11-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 76,
          title: 'The Amazing Spider-Man #19',
          authorId: 1,
          description: 'Spidey Strikes Back! - Sandman and Enforcers',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1964-12-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 77,
          title: 'The Amazing Spider-Man #20',
          authorId: 1,
          description: 'The Coming of the Scorpion! - First appearance of the Scorpion',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-01-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 78,
          title: 'The Amazing Spider-Man #21',
          authorId: 1,
          description: 'Where Flies the Beetle...! - First appearance of the Beetle',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-02-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 79,
          title: 'The Amazing Spider-Man #22',
          authorId: 1,
          description: 'Preeeeeesenting...the Clown, and his Masters of Menace! - Circus of Crime',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-03-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 80,
          title: 'The Amazing Spider-Man #23',
          authorId: 1,
          description: 'The Goblin and the Gangsters - Green Goblin appearance',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-04-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 81,
          title: 'The Amazing Spider-Man #24',
          authorId: 1,
          description: 'Spider-Man Goes Mad! - Mysterio appearance',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-05-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 82,
          title: 'The Amazing Spider-Man #25',
          authorId: 1,
          description: 'Captured By J.Jonah Jameson! - Spencer Smythe and Spider-Slayer',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-06-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 83,
          title: 'The Amazing Spider-Man #26',
          authorId: 1,
          description: "The Man in the Crime-Master's Mask! - First appearance of Crime Master",
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-07-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 84,
          title: 'The Amazing Spider-Man #27',
          authorId: 1,
          description: 'Bring Back My Goblin to Me! - Green Goblin appearance',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-08-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 85,
          title: 'The Amazing Spider-Man #28',
          authorId: 1,
          description: 'The Menace of the Molten Man! - First appearance of the Molten Man',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-09-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 86,
          title: 'The Amazing Spider-Man #29',
          authorId: 1,
          description: 'Never Step on a Scorpion! - Scorpion returns',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-10-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 87,
          title: 'The Amazing Spider-Man #30',
          authorId: 1,
          description: 'The Claws of the Cat! - First appearance of the Cat Burglar',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-11-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 88,
          title: 'The Amazing Spider-Man #31',
          authorId: 1,
          description: 'If This Be My Destiny...! - Classic story begins',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1965-12-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 89,
          title: 'The Amazing Spider-Man #32',
          authorId: 1,
          description: 'Man on a Rampage! - Doctor Octopus',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-01-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 90,
          title: 'The Amazing Spider-Man #33',
          authorId: 1,
          description: 'The Final Chapter! - Iconic "lifting the debris" scene',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-02-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 91,
          title: 'The Amazing Spider-Man #34',
          authorId: 1,
          description: 'The Thrill of the Hunt! - Kraven the Hunter returns',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-03-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 92,
          title: 'The Amazing Spider-Man #35',
          authorId: 1,
          description: 'The Molten Man Regrets...! - Molten Man returns',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-04-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 93,
          title: 'The Amazing Spider-Man #36',
          authorId: 1,
          description: 'When Falls the Meteor! - Looter appearance',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-05-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 94,
          title: 'The Amazing Spider-Man #37',
          authorId: 1,
          description: 'Once Upon A Time, There Was A Robot...! - Professor Stromm',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-06-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 95,
          title: 'The Amazing Spider-Man #38',
          authorId: 1,
          description: 'Just A Guy Named Joe! - Joe Smith',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-07-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 96,
          title: 'The Amazing Spider-Man #39',
          authorId: 1,
          description: 'How Green Was My Goblin! - Green Goblin identity revealed',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-08-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 97,
          title: 'The Amazing Spider-Man #40',
          authorId: 1,
          description: 'Spidey Saves the Day! - End of the Green Goblin (temporarily)',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-09-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 98,
          title: 'The Amazing Spider-Man #41',
          authorId: 1,
          description: 'The Horns of the Rhino! - First appearance of the Rhino',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-10-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99,
          title: 'The Amazing Spider-Man #42',
          authorId: 1,
          description: 'The Birth of a Super-Hero! - Mary Jane Watson face revealed',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-11-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 100,
          title: 'The Amazing Spider-Man #43',
          authorId: 1,
          description: 'Rhino on the Rampage! - Rhino returns',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1966-12-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 101,
          title: 'The Amazing Spider-Man #44',
          authorId: 1,
          description: 'Where Crawls the Lizard! - Lizard returns',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1967-01-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 102,
          title: 'The Amazing Spider-Man #45',
          authorId: 1,
          description: 'Spidey Smashes Out! - Lizard conclusion',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1967-02-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 103,
          title: 'The Amazing Spider-Man #46',
          authorId: 1,
          description: 'The Sinister Shocker! - First appearance of the Shocker',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1967-03-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 104,
          title: 'The Amazing Spider-Man #47',
          authorId: 1,
          description: 'In the Hands of the Hunter! - Kraven the Hunter',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1967-04-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 105,
          title: 'The Amazing Spider-Man #48',
          authorId: 1,
          description: 'The Wings of the Vulture! - Vulture and Blackie Drago',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1967-05-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 106,
          title: 'The Amazing Spider-Man #49',
          authorId: 1,
          description: 'From the Depths of Defeat! - Vulture battle continues',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1967-06-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 107,
          title: 'The Amazing Spider-Man #50',
          authorId: 1,
          description: 'Spider-Man No More! - Classic story where Peter quits being Spider-Man',
          imageUrl: null,
          pages: 22,
          publisherId: 1,
          publishedDate: new Date('1967-07-01'),
          runId: 8,
          variant: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert Trade Paperbacks
    await queryInterface.bulkInsert(
      'TradePaperbacks',
      [
        {
          id: 9,
          title: 'Marvel Masterworks: The Amazing Spider-Man Vol. 1',
          coverImageUrl: null,
          description: 'Collects Amazing Spider-Man #1-10 and Amazing Fantasy #15',
          isbn: '9780785188346',
          publicationDate: new Date('2003-03-01'),
          publisherId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          title: 'Marvel Masterworks: The Amazing Spider-Man Vol. 2',
          coverImageUrl: null,
          description: 'Collects Amazing Spider-Man #11-19 and Annual #1',
          isbn: '9780785188353',
          publicationDate: new Date('2003-08-01'),
          publisherId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          title: 'Marvel Masterworks: The Amazing Spider-Man Vol. 3',
          coverImageUrl: null,
          description: 'Collects Amazing Spider-Man #20-30',
          isbn: '9780785188360',
          publicationDate: new Date('2004-02-01'),
          publisherId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          title: 'Marvel Masterworks: The Amazing Spider-Man Vol. 4',
          coverImageUrl: null,
          description: 'Collects Amazing Spider-Man #31-40 and Annual #2',
          isbn: '9780785188377',
          publicationDate: new Date('2004-08-01'),
          publisherId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          title: 'Marvel Masterworks: The Amazing Spider-Man Vol. 5',
          coverImageUrl: null,
          description: 'Collects Amazing Spider-Man #41-50',
          isbn: '9780785188384',
          publicationDate: new Date('2005-03-01'),
          publisherId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );

    // Insert cross-references for Trade Paperbacks
    await queryInterface.bulkInsert(
      'TradePaperbackComicXRefs',
      [
        // Marvel Masterworks Vol. 1 (TPB ID 9) - Issues #1-10
        {
          tradePaperbackId: 9,
          comicId: 58,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #1
        {
          tradePaperbackId: 9,
          comicId: 59,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #2
        {
          tradePaperbackId: 9,
          comicId: 60,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #3
        {
          tradePaperbackId: 9,
          comicId: 61,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #4
        {
          tradePaperbackId: 9,
          comicId: 62,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #5
        {
          tradePaperbackId: 9,
          comicId: 63,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #6
        {
          tradePaperbackId: 9,
          comicId: 64,
          orderInCollection: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #7
        {
          tradePaperbackId: 9,
          comicId: 65,
          orderInCollection: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #8
        {
          tradePaperbackId: 9,
          comicId: 66,
          orderInCollection: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #9
        {
          tradePaperbackId: 9,
          comicId: 67,
          orderInCollection: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #10

        // Marvel Masterworks Vol. 2 (TPB ID 10) - Issues #11-19
        {
          tradePaperbackId: 10,
          comicId: 68,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #11
        {
          tradePaperbackId: 10,
          comicId: 69,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #12
        {
          tradePaperbackId: 10,
          comicId: 70,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #13
        {
          tradePaperbackId: 10,
          comicId: 71,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #14
        {
          tradePaperbackId: 10,
          comicId: 72,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #15
        {
          tradePaperbackId: 10,
          comicId: 73,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #16
        {
          tradePaperbackId: 10,
          comicId: 74,
          orderInCollection: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #17
        {
          tradePaperbackId: 10,
          comicId: 75,
          orderInCollection: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #18
        {
          tradePaperbackId: 10,
          comicId: 76,
          orderInCollection: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #19

        // Marvel Masterworks Vol. 3 (TPB ID 11) - Issues #20-30
        {
          tradePaperbackId: 11,
          comicId: 77,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #20
        {
          tradePaperbackId: 11,
          comicId: 78,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #21
        {
          tradePaperbackId: 11,
          comicId: 79,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #22
        {
          tradePaperbackId: 11,
          comicId: 80,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #23
        {
          tradePaperbackId: 11,
          comicId: 81,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #24
        {
          tradePaperbackId: 11,
          comicId: 82,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #25
        {
          tradePaperbackId: 11,
          comicId: 83,
          orderInCollection: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #26
        {
          tradePaperbackId: 11,
          comicId: 84,
          orderInCollection: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #27
        {
          tradePaperbackId: 11,
          comicId: 85,
          orderInCollection: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #28
        {
          tradePaperbackId: 11,
          comicId: 86,
          orderInCollection: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #29
        {
          tradePaperbackId: 11,
          comicId: 87,
          orderInCollection: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #30

        // Marvel Masterworks Vol. 4 (TPB ID 12) - Issues #31-40
        {
          tradePaperbackId: 12,
          comicId: 88,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #31
        {
          tradePaperbackId: 12,
          comicId: 89,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #32
        {
          tradePaperbackId: 12,
          comicId: 90,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #33
        {
          tradePaperbackId: 12,
          comicId: 91,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #34
        {
          tradePaperbackId: 12,
          comicId: 92,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #35
        {
          tradePaperbackId: 12,
          comicId: 93,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #36
        {
          tradePaperbackId: 12,
          comicId: 94,
          orderInCollection: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #37
        {
          tradePaperbackId: 12,
          comicId: 95,
          orderInCollection: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #38
        {
          tradePaperbackId: 12,
          comicId: 96,
          orderInCollection: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #39
        {
          tradePaperbackId: 12,
          comicId: 97,
          orderInCollection: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #40

        // Marvel Masterworks Vol. 5 (TPB ID 13) - Issues #41-50
        {
          tradePaperbackId: 13,
          comicId: 98,
          orderInCollection: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #41
        {
          tradePaperbackId: 13,
          comicId: 99,
          orderInCollection: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #42
        {
          tradePaperbackId: 13,
          comicId: 100,
          orderInCollection: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #43
        {
          tradePaperbackId: 13,
          comicId: 101,
          orderInCollection: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #44
        {
          tradePaperbackId: 13,
          comicId: 102,
          orderInCollection: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #45
        {
          tradePaperbackId: 13,
          comicId: 103,
          orderInCollection: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #46
        {
          tradePaperbackId: 13,
          comicId: 104,
          orderInCollection: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #47
        {
          tradePaperbackId: 13,
          comicId: 105,
          orderInCollection: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #48
        {
          tradePaperbackId: 13,
          comicId: 106,
          orderInCollection: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #49
        {
          tradePaperbackId: 13,
          comicId: 107,
          orderInCollection: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, // #50
      ],
      {}
    );
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    // Delete in reverse order of dependencies

    // Delete cross-references first
    await queryInterface.bulkDelete('TradePaperbackComicXRefs', {
      tradePaperbackId: [9, 10, 11, 12, 13],
    });

    // Delete Trade Paperbacks
    await queryInterface.bulkDelete('TradePaperbacks', {
      id: [9, 10, 11, 12, 13],
    });

    // Delete Comics
    await queryInterface.bulkDelete('Comics', {
      id: Array.from({ length: 50 }, (_, i) => 58 + i), // IDs 58-107
    });

    // Delete Run
    await queryInterface.bulkDelete('Runs', {
      id: 8,
    });

    // Delete Creators (Stan Lee with ID 1 is created in another seeder, so only delete Steve Ditko and John Romita Sr.)
    await queryInterface.bulkDelete('Creators', {
      id: [16, 17],
    });
  },
};
