name: Pull Request Checks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - name: Install dependencies
        run: |
          cd api
          npm ci

      - name: Run tests with coverage
        run: |
          cd api
          npm run test:coverage

      - name: Comment PR with coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./api/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Coverage Check
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          result_path: api/coverage/lcov.info
          min_coverage: 70
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - name: Install dependencies
        run: |
          cd api
          npm ci

      - name: Build TypeScript
        run: |
          cd api
          npm run build

      - name: Check build artifacts
        run: |
          cd api
          ls -la out/
          test -f out/index.js || exit 1
