name: API Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - name: Install dependencies
        run: |
          cd api
          npm ci

      - name: Run linter (if configured)
        run: |
          cd api
          npm run lint || echo "No linter configured"
        continue-on-error: true

      - name: Run tests
        run: |
          cd api
          npm test

      - name: Generate coverage report
        run: |
          cd api
          npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./api/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            api/coverage/

      - name: Check coverage threshold
        run: |
          cd api
          npm run test:coverage -- --coverageThreshold='{"global":{"statements":70,"branches":65,"functions":70,"lines":70}}'
